In [ ]:
from Notebook.DSNotebook.NotebookExecutor import NotebookExecutor
nb = NotebookExecutor()
df_Doha_Data = nb.get_data('11111707978183523', '@SYS.USERID', 'True', {}, [])
df_Doha_Data
# The first function parameter refers to the service ID of the dataset.
# @SYS.USERID refers to the user ID of the current user.
# If the Sandbox key is 'false', it is referred to as a dataset, and if it's 'true', then the file is a sandbox file.
# {} refers to the filters applied to the dataset.
# [] refers to the data preparations applied to the dataset.
# After [], users can specify the number of rows to limit the headcount of the dataset with a comma separator.

In [ ]:
from Notebook.DSNotebook.NotebookExecutor import NotebookExecutor
nb = NotebookExecutor()

# Calculate the total number of rows in the DataFrame
total_rows = len(df_Doha_Data)

# Define the batch size
batch_size = 5000

# Calculate the number of batches
num_batches = (total_rows // batch_size) + (1 if total_rows % batch_size != 0 else 0)

# Iterate over the DataFrame in batches
for batch_num in range(num_batches):
    # Calculate the start and end indices of the current batch
    start_idx = batch_num * batch_size
    end_idx = min((batch_num + 1) * batch_size, total_rows)
    
    # Extract the current batch DataFrame
    batch_df = df_Doha_Data.iloc[start_idx:end_idx]
    
    # Write the current batch DataFrame to MySQL database
#     nb.oracle_writer('qauser', 'qauser_123', 'bdboracle.c9lo3db08qkg.ap-south-1.rds.amazonaws.com', '1521', 'ORCL', 'Oracle_Append_1.6M_v1', batch_df)
    nb.mssql_writer('shyam', 'Shy@8746dd8i23', 'bdbcirclek.c9lo3db08qkg.ap-south-1.rds.amazonaws.com', '1433', 'dslabtest', 'MSSQL_Append_1586461 ', batch_df)