In [ ]:
file_path = "Repo/test/new_file.ipynb"
 
file_content = "Test file"
 
with open(file_path, 'w') as file:
    file.write(file_content)

In [2]:
from Notebook.DSNotebook.NotebookExecutor import NotebookExecutor
nb = NotebookExecutor()
df_DS_Lab_Mongo = nb.get_data('11561705559254274', '@SYS.USERID', 'False', {}, [])
df_DS_Lab_Mongo

                                        _id                                    id   brand carFamilyCode transmissionType engineCode                 startTime                  tripDate                   endTime       evTime   evDistance chargeTime      ecoTime      ecoDist    powerTime    powerDist fuelConsumption    fuelSaved     duration       length
0      {'$oid': '653b87d0f80d4f7eb3478e74'}  0036c946-043c-4a75-a2ed-52327bc39201  TOYOTA          679W               MT    2NR-FKE  2021-05-12T13:24:04.000Z  2021-05-12T00:00:00.000Z  2021-05-12T14:03:04.000Z         1276        14842        668         1624        31239          333         4991            2307          656         2625        43779
1      {'$oid': '653b87d0f80d4f7eb3478e75'}  0036c946-043c-4a75-a2ed-52327bc39202  TOYOTA          679W               MT    2NR-FKE  2021-05-15T10:00:00.000Z  2021-05-15T00:00:00.000Z  2021-05-15T10:39:59.000Z         1166        13564        611         1485        28571          178         2670            2108          600         2399        40000
2      {'$oid': '653b87d0f80d4f7eb3478e76'}  0036c946-043c-4a75-a2ed-52327bc39203  TOYOTA          679W               MT    2NR-FKE  2021-05-18T16:11:00.000Z  2021-05-18T00:00:00.000Z  2021-05-18T16:44:07.000Z         1348        15517        711         1571        30000          202         3018            2368          764         2647        45000
3      {'$oid': '653b87d0f80d4f7eb3478e77'}  0036c946-043c-4a75-a2ed-52327bc39204  TOYOTA          679W               MT    2NR-FKE  2021-05-25T11:00:00.000Z  2021-06-04T00:00:00.000Z  2021-05-25T11:38:53.000Z         1302        15000        660         1515        28966          189         2815            2333          741         2333        42000
4      {'$oid': '653b87d0f80d4f7eb3478e78'}  0036c946-043c-4a75-a2ed-52327bc39205  TOYOTA          679W               MT    2NR-FKE  2021-05-21T09:11:00.000Z  2021-05-21T00:00:00.000Z  2021-05-21T09:35:58.000Z         1317        15185        642         1529        29286          184         2746            2216          693         2158        41000
...                                     ...                                   ...     ...           ...              ...        ...                       ...                       ...                       ...          ...          ...        ...          ...          ...          ...          ...             ...          ...          ...          ...
17679  {'$oid': '653b87d5f80d4f7eb347d383'}  0036c946-043c-4a75-a2ed-52327bc39216  TOYOTA          831W              CVT   A25A-FXS  2021-03-20T16:00:00.000Z  2021-03-20T00:00:00.000Z  2021-03-20T16:25:24.000Z  274051.9174  3166052.301    82460.9  143860.1486  3075990.223   973.542029   26767.2442     319656.9159   23380.9413  144817.4254  6102962.706
17680  {'$oid': '653b87d5f80d4f7eb347d384'}  0036c946-043c-4a75-a2ed-52327bc39217  TOYOTA          831W              CVT   A25A-FXS  2021-03-05T09:22:00.000Z  2021-03-05T00:00:00.000Z  2021-03-05T09:28:02.000Z  274067.3552  3166230.649   82465.53  143868.2029  3076162.624   973.585942  26768.59159     319674.8781  23382.22739  144825.4793  6103305.698
17681  {'$oid': '653b87d5f80d4f7eb347d385'}  0036c946-043c-4a75-a2ed-52327bc39218  TOYOTA          831W              CVT   A25A-FXS  2021-02-12T13:00:00.000Z  2021-02-12T00:00:00.000Z  2021-02-12T14:10:31.000Z   274082.793  3166408.996   82470.16  143876.2572  3076335.024  973.6298551  26769.93899     319692.8403  23383.51348  144833.5332  6103648.691
17682  {'$oid': '653b87d5f80d4f7eb347d386'}  0036c946-043c-4a75-a2ed-52327bc39219  TOYOTA          831W              CVT   A25A-FXS  2021-02-04T07:00:00.000Z  2021-02-04T00:00:00.000Z  2021-02-04T07:37:30.000Z  274098.2309  3166587.344   82474.79  143884.3116  3076507.424  973.6737681  26771.28638     319710.8025  23384.79957  144841.5871  6103991.684
17683  {'$oid': '653b87d5f80d4f7eb347d387'}  0036c946-043c-4a75-a2ed-52327bc39220  TOYOTA          831W              CVT   A25A-FXS  2021-02-12T13:33:00.000Z  2021-02-12T00:00:00.000Z  2021-02-12T13:54:21.000Z  274113.6687  3166765.692   82479.42  143892.3659  3076679.825  973.7176812  26772.63377     319728.7646  23386.08565   144849.641  6104334.676

[17684 rows x 20 columns]